version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  memcached:
    image: memcached:alpine
    ports:
      - 11211:11211
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgres

volumes:
  postgres_data:
