# Generated by Django 5.0.3 on 2024-03-30 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('status', models.CharField(max_length=63)),
                ('priority', models.CharField(max_length=63)),
                ('section', models.CharField(max_length=63)),
                ('installed_size', models.PositiveIntegerField()),
                ('maintainer', models.CharField(max_length=255)),
                ('original_maintainer', models.CharField(max_length=255)),
                ('architecture', models.CharField(max_length=63)),
                ('version', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('homepage', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('depends', 'Depends'), ('pre-depends', 'Pre-Depends'), ('recommends', 'Recommends')], max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.package')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_dependencies', to='core.package')),
            ],
            options={
                'unique_together': {('source', 'target', 'type')},
            },
        ),
    ]
