# Generated by Django 5.0.3 on 2024-03-31 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_package_confiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='confiles',
        ),
        migrations.CreateModel(
            name='Confile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confiles', to='core.package')),
            ],
        ),
    ]
