# Generated by Django 5.0.3 on 2024-03-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_package_confiles_confile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confile',
            new_name='Conffile',
        ),
    ]
