# Generated by Django 5.0.3 on 2024-03-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_confile_conffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='source',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
