# Generated by Django 5.0.3 on 2024-03-31 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_package_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='provides',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='package',
            name='python_version',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='recommends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='package',
            name='replaces',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='type',
            field=models.CharField(choices=[('depends', 'Depends'), ('pre-depends', 'Pre-Depends')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='source',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
